nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
Previously, io and processing were on the same "mono" executor; the
mono exists to ensure the OkHttp response can be closed on the same
thread it was opened on. But using it for processing as well as io
can result in contended pipelines where the processing is starved
as io work dominates.
This creates a new mono that is given to processing. In principle
(and functionally), a regular rx computation scheduler works, but
a single thread for now makes it easier to reason about offset
checkpointing and ordered processing of stream batches.
=> Place io and processing on different schedulers.

gradle.properties, nakadi-java-client/build.gradle, nakadi-java-client/src/main/java/nakadi/EmptyTokenProvider.java, nakadi-java-client/src/main/java/nakadi/ExecutorServiceSupport.java, nakadi-java-client/src/main/java/nakadi/ResourceOptions.java, nakadi-java-client/src/main/java/nakadi/TokenProvider.java, nakadi-java-metrics/build.gradle, nakadi-java-zign/build.gradle, nakadi-java-zign/src/main/java/nakadi/token/zign/TokenProviderZign.java
=> Add a Zign token provider with a background refresh

gradle/libs.gradle, nakadi-java-client/build.gradle, nakadi-java-client/src/main/java/nakadi/EventResource.java, nakadi-java-client/src/main/java/nakadi/ResourceOptions.java, nakadi-java-client/src/test/java/nakadi/EventResourceTest.java
This will ask the token provider to supply the API scope for writing
events.
=> Use the event write scope for event sending.

nakadi-java-client/src/main/java/nakadi/OkHttpResource.java, nakadi-java-client/src/test/java/nakadi/OkHttpResourceTest.java
Also, extract throwing methods to reduce duplication.
=> Fix tests on throwing requests.

nakadi-java-client/src/main/java/nakadi/OkHttpResource.java
This puts all http call chains inside an observable, which allows them
to be constructed once, and avoid bugs where one side of the retry null
conditional is different to the other, or drifts. The retry is added
to the observable if it's not null and not finished.
The not finished check stops unusable retries being configured. Apart
from avoiding no-op retries, it's indicative of a caller bug where
they're recycling retries across requests (retries have state). This
is flagged as a warning log for now; it may be better to throw an
exception; we'll see.
=> Clean up http call chains.

nakadi-java-zign/build.gradle, nakadi-java-zign/src/main/java/nakadi/token/zign/TokenProviderZign.java, nakadi-java-zign/src/main/resources/logback-test.xml
=> 	Fix zign call path, add default scopes

nakadi-java-client/src/main/java/nakadi/EventTypeResource.java, nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java, nakadi-java-client/src/main/java/nakadi/SubscriptionResource.java, nakadi-java-client/src/main/java/nakadi/SubscriptionResourceReal.java
=> Add some optional finders.

README.md, nakadi-java-client/src/main/java/nakadi/AuthorizationException.java, nakadi-java-client/src/main/java/nakadi/ClientException.java, nakadi-java-client/src/main/java/nakadi/ConflictException.java, nakadi-java-client/src/main/java/nakadi/HttpException.java, nakadi-java-client/src/main/java/nakadi/InvalidException.java, nakadi-java-client/src/main/java/nakadi/LoggingBusinessEventObserverProvider.java, nakadi-java-client/src/main/java/nakadi/LoggingDataChangeEventObserver.java, nakadi-java-client/src/main/java/nakadi/LoggingDataChangeEventObserverProvider.java, nakadi-java-client/src/main/java/nakadi/LoggingStreamObserverProvider.java, nakadi-java-client/src/main/java/nakadi/LoggingUndefinedEventObserver.java, nakadi-java-client/src/main/java/nakadi/LoggingUndefinedEventObserverProvider.java, nakadi-java-client/src/main/java/nakadi/NetworkException.java, nakadi-java-client/src/main/java/nakadi/OkHttpResource.java, nakadi-java-client/src/main/java/nakadi/PreconditionFailedException.java, nakadi-java-client/src/main/java/nakadi/RateLimitException.java, nakadi-java-client/src/main/java/nakadi/ServerException.java, nakadi-java-client/src/main/java/nakadi/StreamProcessor.java, nakadi-java-client/src/main/java/nakadi/TypeLiterals.java, nakadi-java-client/src/test/java/nakadi/OkHttpResourceTest.java
Patches after using the client in a Play Scala app.
=> Some improvements.

README.md
=> Replace resourceTokenProvider with  tokenProvider

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java, nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java
=> Test that StreamObserverProviders are not defaulted.

nakadi-java-client/src/main/java/nakadi/EventMappedSupport.java, nakadi-java-client/src/main/java/nakadi/EventResourceReal.java, nakadi-java-client/src/main/java/nakadi/EventStreamBatch.java, nakadi-java-client/src/main/java/nakadi/EventType.java, nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java, nakadi-java-client/src/main/java/nakadi/ExceptionSupport.java, nakadi-java-client/src/main/java/nakadi/JsonBatchSupport.java, nakadi-java-client/src/main/java/nakadi/NakadiClient.java, nakadi-java-client/src/main/java/nakadi/NakadiClientMain.java, nakadi-java-client/src/main/java/nakadi/Problem.java, nakadi-java-client/src/main/java/nakadi/QueryParams.java, nakadi-java-client/src/main/java/nakadi/RegistryResource.java, nakadi-java-client/src/main/java/nakadi/ResourceCollectionEmpty.java, nakadi-java-client/src/main/java/nakadi/ResourceOptions.java, nakadi-java-client/src/main/java/nakadi/SecuritySupport.java, nakadi-java-client/src/main/java/nakadi/StreamConfiguration.java, nakadi-java-client/src/main/java/nakadi/StreamCursorContextReal.java, nakadi-java-client/src/main/java/nakadi/StreamProcessor.java, nakadi-java-client/src/main/java/nakadi/Subscription.java, nakadi-java-client/src/main/java/nakadi/SubscriptionOffsetObserver.java, nakadi-java-client/src/main/java/nakadi/SubscriptionResourceReal.java, nakadi-java-client/src/main/java/nakadi/UriBuilder.java
Also remove guava where it's not strictly needed.
=> Give StreamProcessor scheduler threads specific names.

CHANGES.md, nakadi-java-client/src/main/java/nakadi/OkHttpResource.java, nakadi-java-client/src/main/java/nakadi/StreamConfiguration.java, nakadi-java-client/src/main/java/nakadi/StreamProcessor.java, nakadi-java-client/src/main/java/nakadi/StreamResourceSupport.java, nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java, nakadi-java-client/src/test/java/nakadi/StreamResourceSupportTest.java, nakadi-java-client/src/test/resources/data-change-event-batch-oneline-1.json
=> Applies custom headers to event and subscription consumers.

nakadi-java-client/src/main/java/nakadi/BusinessEventMapped.java, nakadi-java-client/src/main/java/nakadi/DataChangeEvent.java, nakadi-java-client/src/main/java/nakadi/UndefinedEventMapped.java
To be able to check, that children is the right subtype of Event we need subclasses of Event to pass generic type to Event.
=> Pass Event's children generic type to Event.

nakadi-java-client/src/main/java/nakadi/EventTypeResource.java, nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java, nakadi-java-client/src/main/java/nakadi/Partition.java, nakadi-java-client/src/test/java/nakadi/EventTypeResourceRealTest.java, nakadi-java-client/src/test/resources/cursor-lag-response-ok.json
=> Adds support for requesting cursor lag.

nakadi-java-client/src/main/java/nakadi/EventTypeResource.java, nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java, nakadi-java-client/src/test/java/nakadi/EventTypeResourceRealTest.java, nakadi-java-client/src/test/resources/partition-unconsumed-response-ok.json
=> Adds support for requesting consumed_offset per partition.

nakadi-java-client/src/main/java/nakadi/EventResourceReal.java
=> Coerces raw string event posting to UTF-8.

nakadi-java-client/src/main/java/nakadi/ExceptionSupport.java, nakadi-java-client/src/main/java/nakadi/OkHttpResource.java, nakadi-java-client/src/main/java/nakadi/Problem.java
The server doesn't return the correct response code or structure
for some auth issues. This is hack to inspect the response returned
by the server to allow auth errors to be retryable and provide
usable diagnostics to end users.
=> Works around  https://github.com/zalando/nakadi/issues/645.

nakadi-java-gson/src/main/java/nakadi/json/gson/GsonSupport.java
=> Makes GsonSupport extension public.

nakadi-java-client/src/main/java/nakadi/EventType.java
The EventType's field name for default_statistic was wrong so
marshalling failed. This changes the field name but leaves the
getter method name as is.
For #203.
=> Fixes JSON fieldname for event type statistics.

nakadi-java-client/src/main/java/nakadi/BatchItemResponseCollection.java, nakadi-java-client/src/main/java/nakadi/CursorCollection.java, nakadi-java-client/src/main/java/nakadi/CursorCommitResultCollection.java, nakadi-java-client/src/main/java/nakadi/CursorDistanceCollection.java, nakadi-java-client/src/main/java/nakadi/EnrichmentStrategyCollection.java, nakadi-java-client/src/main/java/nakadi/EventResourceReal.java, nakadi-java-client/src/main/java/nakadi/EventTypeCollection.java, nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java, nakadi-java-client/src/main/java/nakadi/EventTypeSchemaCollection.java, nakadi-java-client/src/main/java/nakadi/PartitionCollection.java, nakadi-java-client/src/main/java/nakadi/RegistryResource.java, nakadi-java-client/src/main/java/nakadi/ResourceCollection.java, nakadi-java-client/src/main/java/nakadi/ResourceCollectionEmpty.java, nakadi-java-client/src/main/java/nakadi/SubscriptionCollection.java, nakadi-java-client/src/main/java/nakadi/SubscriptionCursorCollection.java, nakadi-java-client/src/main/java/nakadi/SubscriptionEventTypeStatsCollection.java, nakadi-java-client/src/main/java/nakadi/SubscriptionResourceReal.java, nakadi-java-client/src/main/java/nakadi/ValidationStrategyCollection.java, nakadi-java-client/src/test/java/nakadi/EventResourceRealTest.java, nakadi-java-client/src/test/java/nakadi/ResourceCollectionTest.java
Some Nakadi servers send back relative paging urls. This resolves
them against the base uri configured on the client.
For #204.
=> Checks if the next pagination url is relative.

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
This looks for InterruptedIOException coming up from the
rxjava/okio layers and re-interrupts the thread without
logging the trace.
This error can happen normally when the stream processor
is shutting down its executors but the processor is still
reading via its flowable. The log error is a bit of a
red-herring, so skipping it here.
For #186.
=> Reinterrupt and don't log interrupted from the http layer.

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
This calls ExecutorServiceSupport.shutdown directly on the io
and processing executor services that are wrapped as RxJava
Schedulers. Calling shutdown on the Scheduler wrappers doesn't
release threads which can leave them in place (eg without this
change this can stop the jvm shutting down cleanly).
For #186.
=> Stops ExecutorServices wrapped as Schedulers directly.

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
This waits for up to 60s on a latch to allow the stream
processor to commence. The latch is decremented after the
stream start is called from inside the executor (stream
start happens as an async task. Both the start and stop
methods coordinate on the latch.
For #186.
=> Adds a latch around the start of the StreamProcessor.

nakadi-java-client/src/main/java/nakadi/ExceptionSupport.java, nakadi-java-client/src/test/java/nakadi/ExceptionSupportTest.java
=> Stop retrying 404 NotFound exceptions

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java, nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java
=> Fix maxRetry attempts for stream configuration

.gitignore, README.md, nakadi-java-client/src/main/java/nakadi/EventResource.java, nakadi-java-client/src/main/java/nakadi/EventResourceReal.java, nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java
=> Allows headers to be sent with posted events

nakadi-java-client/src/main/java/nakadi/SubscriptionOffsetCheckpointer.java
This logs the right message for a stale cursor update that is
ignored by the server versus one where the server moved the
cursor forward.
For #244.
=> Fixes log message for cursor updates.

nakadi-java-client/src/main/java/nakadi/EventResourceReal.java, nakadi-java-client/src/main/java/nakadi/GsonSupport.java, nakadi-java-client/src/main/java/nakadi/JsonSupport.java, nakadi-java-client/src/test/java/nakadi/GsonSupportTest.java, nakadi-java-client/src/test/java/nakadi/JsonSupportNoop.java, nakadi-java-client/src/test/java/nakadi/OkHttpResourceTest.java, nakadi-java-gson/src/main/java/nakadi/json/gson/GsonSupport.java
=> Sends flattened JSON when posting an event.

nakadi-java-client/src/main/java/nakadi/AuthorizationAttribute.java, nakadi-java-client/src/main/java/nakadi/EventType.java, nakadi-java-client/src/main/java/nakadi/EventTypeAuthorization.java, nakadi-java-client/src/test/java/nakadi/EventTypeTest.java, nakadi-java-client/src/test/resources/event-type-1.json
=> Adds authorizations to event types.

nakadi-java-zign/build.gradle
=> Excludes test jar from nakadi-java-zign.

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
The hanlder warns on a RejectedExecutionException as this can happen
between one processor stopping and new one starting if the old one
is canceled mid-flight.
For #225.
=> Routes rxjava undeliverable exceptions to a handler.

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
This removes the wait on start latch from the stop call. In earlier
versions, stop was blocked on start to ensure stop didn't pass
through while the processor was still starting and fail to shutdown the
processor. More recently, changes to start and stop logic seem to
avoid the need for this.
Also changes the start latch await time to a non-standard number (63s) 
to make it easier to distinguish in the future.
=> Avoids StreamProcessor.stop waiting on start completion.

gradle/libs.gradle, nakadi-java-client/dependencies.lock, nakadi-java-client/src/main/java/nakadi/NakadiClient.java, nakadi-java-client/src/main/java/nakadi/OkHttpResource.java, nakadi-java-client/src/main/java/nakadi/Resource.java, nakadi-java-gson/dependencies.lock
=>  Allows the request write timeout to be set.

nakadi-java-client/src/main/java/nakadi/EventTypeResource.java, nakadi-java-client/src/main/java/nakadi/MetricsResource.java, nakadi-java-client/src/main/java/nakadi/SubscriptionResource.java
Original javadocs seem to be copy-pasted.
=> Correct thrown exception javadoc

nakadi-java-client/src/main/java/nakadi/EventMetadata.java, nakadi-java-client/src/test/java/nakadi/EventMetadataTest.java, nakadi-java-client/src/test/java/nakadi/EventResourceRealTest.java, nakadi-java-client/src/test/java/nakadi/JsonBatchSupportTest.java, nakadi-java-client/src/test/resources/business-event-batch-span-ctx.json, nakadi-java-client/src/test/resources/data-change-event-batch-span-ctx.json
=> Adds span tracing to event metadata.

nakadi-java-client/src/main/java/nakadi/Subscription.java, nakadi-java-client/src/main/java/nakadi/SubscriptionAuthorization.java
Adds ability to include the authorization section when creating a subscription.
=> Authorization for Subscriptions

.circleci/config.yml, nakadi-java-client/src/test/java/nakadi/SubscriptionResourceRealTest.java
Adds test for SubscriptionAuthorization.
=> Adds test for SubscriptionAuthorization.

README.md
document fix: removed ; from builder pipeline
=> document fix: removed ; from builder pipeline

nakadi-java-client/src/main/java/nakadi/Problem.java
- Replaces param with code in Problem  #376 
- Tidies up the raw Problem type javadoc
- Fixes the contract retryable Problem type Javadoc
=> Fixes to Problem types
