dehora/nakadi-java

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java

Previously this was called outsider the observable, which meant if
it failed, the stream processor would fail instead of entering a
retry/restart cycle.

Move event type/subscription resolution to stream resource factory.

---

nakadi-java-client/src/main/java/nakadi/NakadiClient.java
nakadi-java-client/src/main/java/nakadi/OkHttpResponseBody.java
nakadi-java-client/src/main/java/nakadi/StreamExceptionSupport.java
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java

Adds a timeout that will fire if the keepaive is not seen within
the configured (or default) batch limit time, plus a grace period.
If the TimeoutException is thrown the client will disconnect and
resume the stream by reconnecting. This protects against server
weirdness but also against half-open connections.
The observable's using() setup runs on a single threaded scheduler.
OkHttp needs to close a response on the same thread that opened it
otherwise we'll get errors and may leak resources. Using a single
thread scheduler allows that to happen whereas the default/io/compute
schedulers all use a thead pool that often has the dispose step
trying to close the OkHttp response on the wrong thread.

Handle the server not sending keepalives within batch limit time

---

nakadi-java-client/src/main/java/nakadi/NakadiClient.java

Internally, except for one scenario, API handling is abstracted
away from Gson and could use any provider. There's arguably little
value in allowing pluggable JSON support for a client that's
focused on production/ops behaviour - it just provides a vector for
errors. For example, supplying a JSON option that is not configured
to skip nulls won't work with the server API in certain cases. As
another example cursor JSON in headers should be whitespace
compressed. The internal JSON provider abstraction is kept as that's
useful for organizing the code.

Remove the option to configure the JSON provider.

---

nakadi-java-client/src/main/java/nakadi/BusinessEventMapped.java
nakadi-java-client/src/main/java/nakadi/EventMappedSupport.java
nakadi-java-client/src/main/java/nakadi/JsonBatchSupport.java
nakadi-java-client/src/main/java/nakadi/UndefinedEventMapped.java
nakadi-java-client/src/test/java/nakadi/EventResourceTest.java
nakadi-java-client/src/test/java/nakadi/JsonBatchSupportTest.java

This allows undefined and business events to be declared with
a generic type instead of a fixed Map<String, Object>. The
previous map option would force client users to reserialise
and deserialise the map to the domain object they're interested
in using.
Getting this to work such that a use can set their custom event
data into the "data" field and have that information lifted into
the top level JSON of the posted event, and have top level JSON
data received in a stream batch mapped down into the same "data"
requires some ugly serialization and deserialization (serdes)
hacks when those types are detected. That's the nature of the HTTP
API we have to work with. Otherwise we'd either have to, drop the
idea of having support for undefined and business, pass around
non-domain types (strings, …

Make UndefinedEventMapped and BusinessEventMapped generic.

---

nakadi-java-client/src/main/java/nakadi/ExecutorServiceSupport.java
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java

All 3 executors are now shutdown on stop() being called. This avoids
the JVM getting stuck on shutdown due to the executor threads.

Shutdown all stream processing executors.

---

CHANGES.md
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
nakadi-java-client/src/main/java/nakadi/StreamResourceSupport.java
nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java
nakadi-java-client/src/test/java/nakadi/StreamResourceSupportTest.java

This will ask the token provider to supply the API scope for reading
events.

Use the event read scope for event streaming.

---

nakadi-java-client/src/main/java/nakadi/EventMappedSupport.java
nakadi-java-client/src/main/java/nakadi/EventRecord.java
nakadi-java-client/src/main/java/nakadi/EventResource.java
nakadi-java-client/src/main/java/nakadi/EventResourceReal.java
nakadi-java-client/src/main/java/nakadi/Resources.java
nakadi-java-client/src/test/java/nakadi/EventResourceRealTest.java
nakadi-java-zign/src/test/java/nakadi/token/zign/TokenProviderZignTest.java

This replaces the list and varargs options with a list and
and a single event send methods. The varargs were handy but
provided too many call options and also causing warnings
because the generic event type wasn't reifable (since a
varargs list is converted to a T[] which wipes the type
information and would be illegal if we actually wrote that
out; but since the compiler is doing it we get a warning
instead).
The constraint that the send methods take a wilcard extending
Event has also been lifted, to allow any type to be used.

Simplify event sending methods.

---

nakadi-java-client/src/main/java/nakadi/EventTypeCollection.java
nakadi-java-client/src/main/java/nakadi/EventTypeResource.java
nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java
nakadi-java-client/src/main/java/nakadi/PartitionCollection.java
nakadi-java-client/src/main/java/nakadi/Resources.java
nakadi-java-client/src/test/java/nakadi/EventTypeResourceRealTest.java

This uses the default scopes where documented, and a best guess
where not documented for event type scopes. The scopes() method
on the EventTypeResource allows a custom scope to be passed in
and can be changed per request invocation. If there's no custom
scope, the default for the request is applied.
For #48.

Allow scopes and custom scopes to be set for event types.

---

nakadi-java-client/src/main/java/nakadi/EventResource.java
nakadi-java-client/src/main/java/nakadi/EventResourceReal.java
nakadi-java-client/src/test/java/nakadi/EventResourceRealTest.java

The scopes() method on the EventResource allows a custom scope to be passed in
and can be changed per request invocation. If there's no custom scope, the
default for the request is applied.
For #48.

Allow custom scopes to be set for event sending.

---

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
nakadi-java-client/src/main/java/nakadi/StreamResourceSupport.java
nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java
nakadi-java-client/src/test/java/nakadi/StreamResourceSupportTest.java

The scopes() method on the StreamProcessor.Builder allows a custom scope
to be passed in. If there's no custom scope, the default for the request
is applied.
For #48.

Allow custom scopes to be set for event streaming.

---

nakadi-java-client/src/main/java/nakadi/CursorCommitResultCollection.java
nakadi-java-client/src/main/java/nakadi/Resources.java
nakadi-java-client/src/main/java/nakadi/SubscriptionCollection.java
nakadi-java-client/src/main/java/nakadi/SubscriptionCursorCollection.java
nakadi-java-client/src/main/java/nakadi/SubscriptionEventTypeStatsCollection.java
nakadi-java-client/src/main/java/nakadi/SubscriptionResource.java
nakadi-java-client/src/main/java/nakadi/SubscriptionResourceReal.java
nakadi-java-client/src/test/java/nakadi/SubscriptionResourceRealTest.java

This uses the default scopes where documented, and a best guess where not 
documented for event type scopes. The scopes() method on the 
SubscriptionResource allows a custom scope to be passed in and can be changed 
per request invocation. If there's no custom scope, the default for the request 
is applied.
For #48.

Allow custom scopes to be set for subscriptions.

---

nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java
nakadi-java-client/src/main/java/nakadi/HealthCheckResource.java
nakadi-java-client/src/main/java/nakadi/OkHttpResource.java
nakadi-java-client/src/main/java/nakadi/RegistryResource.java
nakadi-java-client/src/main/java/nakadi/Resource.java
nakadi-java-client/src/main/java/nakadi/StreamConnectionRetry.java
nakadi-java-client/src/main/java/nakadi/SubscriptionResourceReal.java

This allows the resource to have a backoff policy object set that will
be applied on the request method. If no backoff is set, the request
is called directly.
For #27.

Support backoffs on http requests.

---

nakadi-java-client/src/main/java/nakadi/ExceptionSupport.java
nakadi-java-client/src/main/java/nakadi/OkHttpResource.java
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
nakadi-java-client/src/test/java/nakadi/OkHttpResourceTest.java

Fix a bug in one of OkHttpResource's throwable calls and add tests to cover it.

Add tests for status code to exception mappings

---

nakadi-java-client/src/main/java/nakadi/StreamConfiguration.java
nakadi-java-client/src/main/java/nakadi/StreamConnectionRetry.java
nakadi-java-client/src/test/java/nakadi/StreamConfigurationTest.java
nakadi-java-zign/build.gradle

When a client handling a partition goes away, the other running clients
will compete to grab it once they wake up and retry. They work by retrying
every N seconds to see if a partition is available and then fall back to
sleep if none are. The aim here is to avoid any need for special level
handling to manage down the number of client connections by the caller.
It should be ok to run the client across your very large microservices
cluster such that even for just a few partitions, they won't hammer the
broker.
This stops the client accepting a value that could cause too many requests;
picking 1s for now, might need to change later.
For #83.

Reject retry delays that are less than 1s.

---

nakadi-java-client/src/main/java/nakadi/ExponentialRetry.java
nakadi-java-client/src/test/java/nakadi/ExponentialRetryTest.java

This provides an option to bound retries by time regardless of the number of
attempts. Event producers that want to bound the total amount of time sending
an event before giving up, and the subscription stream checkpointer are the
main examples in the client that would find it useful to exist based on time
elapse rather than number of attempts.
For #81.

Extend RetryPolicy to support max time backoff.

---

CHANGES.md
README.md
gradle.properties
nakadi-java-client/src/main/java/nakadi/StreamResourceSupport.java
nakadi-java-client/src/main/java/nakadi/Version.java

The API definition documents only accepting application/x-json-stream,
but current Nakadi servers reject it with a 406 (they accept no
media type or application/json). Patching on the client for now until
the server definition/implementation is fixed.
For #98.

Replace application/x-json-stream with application/json.

---

CHANGES.md
README.md
gradle.properties
nakadi-java-client/src/main/java/nakadi/LoggingStreamObserver.java
nakadi-java-client/src/main/java/nakadi/StreamBatchRecordBufferingSubscriber.java
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
nakadi-java-client/src/main/java/nakadi/Version.java

This seemed to have been fixed for Observable.from in
ReactiveX/RxJava#3893, as reported in
https://github.com/ReactiveX/RxJava/issues/3892but it's happening
here. Adding onBackpressureBuffer after switchIfEmpty looks to
help the situation as per this patch
For #100.

Add back pressure buffering to stream processor.

---

nakadi-java-client/src/main/java/nakadi/EventMappedSupport.java

The previous check allowed Object to be matched to
the undefined type; this reverses it to make sure
the well known category classes are in fact assignable.

Fix is assignable check for well know categories.

---

nakadi-java-client/src/main/java/nakadi/EventMetadata.java
nakadi-java-client/src/main/java/nakadi/EventType.java
nakadi-java-client/src/main/java/nakadi/EventTypeResource.java
nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java
nakadi-java-client/src/main/java/nakadi/EventTypeSchema.java
nakadi-java-client/src/main/java/nakadi/EventTypeSchemaCollection.java
nakadi-java-client/src/main/java/nakadi/Experimental.java

Once the feature is fully available, `Experimental` can be removed.

Add experimental access to schema and schema versions.

---

nakadi-java-client/src/main/java/nakadi/EventContentSupplier.java
nakadi-java-client/src/main/java/nakadi/EventResource.java
nakadi-java-client/src/main/java/nakadi/EventResourceReal.java
nakadi-java-client/src/main/java/nakadi/OkHttpResource.java

This allows raw strings to be submitted as well as objects. Without
detecting the string as a string, it will be double escaped by gson.
The feature's experimental and the implementation will probably
change if kept around.

Support sending events as raw strings.

---

nakadi-java-client/src/main/java/nakadi/BatchItemResponse.java
nakadi-java-client/src/main/java/nakadi/BatchItemResponseCollection.java
nakadi-java-client/src/main/java/nakadi/EventResource.java
nakadi-java-client/src/main/java/nakadi/EventResourceReal.java
nakadi-java-client/src/main/java/nakadi/GsonSupport.java
nakadi-java-client/src/main/java/nakadi/JsonSupport.java
nakadi-java-client/src/main/java/nakadi/OkHttpResource.java
nakadi-java-client/src/main/java/nakadi/Resource.java
nakadi-java-client/src/test/java/nakadi/EventResourceRealTest.java
nakadi-java-client/src/test/resources/err_batch_item_response_array.json

This supports the case when the server returns 207 or 422 for an
event post. It also provides a convenience method on EventResource
that returns a BatchItemResponseCollection instead of having to
marshal the Response content from the other send methods.
For #116.

Handle batch item responses for event posting.

---

nakadi-java-client/src/main/java/nakadi/StreamConfiguration.java
nakadi-java-client/src/main/java/nakadi/StreamResourceSupport.java
nakadi-java-client/src/test/java/nakadi/StreamResourceSupportTest.java

A batch limit of 0 isn't a useful value despite the the API definition
describing it. Instead the server never sends events if batch limit is 0
which is a silent bug. This changes the client to ignore 0 (or lower)
values for batch limit. A future pr prior to 1.0.0 might result in an
exception being thrown but for now ignoring the value keeps with the
current client behaviour.
For #125.

Ignores batch limit values set to 0 or less.

---

README.md
nakadi-java-client/src/main/java/nakadi/Cursor.java
nakadi-java-client/src/main/java/nakadi/NakadiException.java
nakadi-java-client/src/main/java/nakadi/Subscription.java
nakadi-java-client/src/test/java/nakadi/SubscriptionTest.java

This allows clients to create a Subscription from a known set of
partition offsets. The cursor list is validated to be non-null
and not empty, otherwise validations are left to the server.
For #139.

Supports initial_cursors for creating Subscriptions.

---

nakadi-java-client/src/main/java/nakadi/EventMappedSupport.java
nakadi-java-client/src/test/java/nakadi/EventMappedSupportTest.java
nakadi-java-client/src/test/java/nakadi/EventResourceRealTest.java
nakadi-java-client/src/test/java/nakadi/OkHttpResourceTest.java

Building up a json object tree for business events instead of a
serialization roundtrip avoids ints being coerced to floats by
Gson.
For #119.

Fixes integers in BusinessEventMapped being serialised to floats.

---

README.md
nakadi-java-client/src/main/java/nakadi/SecuritySupport.java
nakadi-java-client/src/test/java/nakadi/SecuritySupportTest.java

The existing classpath resolver only works when the classpath is
on the filesystem (it scans for files in the supplied folder).
This allows a specific cert ending in pem or crt to be stated,
which should work better with regular classpath resource resolution.
It's preferable to load certs from the keystore. The file and
classpath options are primarily for letting people develop locally
with self-signed certs.
For #126.

Allows a specific cert to be loaded from the classpath.

---

nakadi-java-client/src/main/java/nakadi/OkHttpResource.java
nakadi-java-client/src/main/java/nakadi/ProblemSupport.java
nakadi-java-client/src/test/java/nakadi/ProblemSupportTest.java
nakadi-java-client/src/test/resources/nakadi-645-invalid-problem-400.json
nakadi-java-client/src/test/resources/nakadi-645-invalid-problem-401.json

The server doesn't return the correct response code or structure
for some auth issues. This is hack to inspect the response returned
by the server to allow auth errors to be retryable and provide
usable diagnostics to end users.
For #188.
See also: 3f3d2660be1b4e70eafb0033e6a9b700e44d1523.
See: zalando/nakadi#645

Works around zalando/nakadi#645.

---

nakadi-java-client/src/main/java/nakadi/ProblemSupport.java
nakadi-java-client/src/test/java/nakadi/ProblemSupportTest.java

The server doesn't return the correct response code or structure for some auth issues. 
For #188.
See also: #189.
See: zalando/nakadi#645

Uses unexpected json structure to workaround zalando/nakadi#645.

---

nakadi-java-client/src/main/java/nakadi/NakadiClient.java
nakadi-java-client/src/test/java/nakadi/JsonSupportNoop.java
nakadi-java-client/src/test/java/nakadi/NakadiClientTest.java

This allows third party setting of JsonSupport and is useful for
cases where control over marshalling/serialization is needed, eg
when using Jackson or Gson custom annotations.
For #182.

Allows JsonSupport implementation to be supplied to the client.

---

nakadi-java-client/src/main/java/nakadi/SubscriptionOffsetCheckpointer.java
nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java
nakadi-java-client/src/test/java/nakadi/SubscriptionOffsetCheckpointerTest.java

The constructor option was replaced with a fluent setter. This
removes the constructor in advance of 0.9.0.

Removes deprecated means to suppress invalid exceptions.

---

nakadi-java-client/src/main/java/nakadi/EventType.java
nakadi-java-client/src/main/java/nakadi/EventTypeStatistics.java
nakadi-java-client/src/test/java/nakadi/EventTypeTest.java

This is useful for implicit creation of partition count and should
only be used when creating a new event type.

Allows the eventTypeStatistic to be set on an EventType.

---

nakadi-java-client/src/main/java/nakadi/BatchItemResponse.java
nakadi-java-client/src/test/java/nakadi/BatchItemResponseTest.java
nakadi-java-client/src/test/java/nakadi/test/BatchItemResponseVisibilityTest.java

Makes publishing status and steps visible in BatchItemResponse.

---

nakadi-java-client/src/main/java/nakadi/EmptyTokenProvider.java
nakadi-java-client/src/main/java/nakadi/EventResource.java
nakadi-java-client/src/main/java/nakadi/EventResourceReal.java
nakadi-java-client/src/main/java/nakadi/EventType.java
nakadi-java-client/src/main/java/nakadi/EventTypeResource.java
nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java
nakadi-java-client/src/main/java/nakadi/ResourceOptions.java
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
nakadi-java-client/src/main/java/nakadi/StreamProcessorRequestFactory.java
nakadi-java-client/src/main/java/nakadi/StreamResourceSupport.java
nakadi-java-client/src/main/java/nakadi/SubscriptionResource.java
nakadi-java-client/src/main/java/nakadi/SubscriptionResourceReal.java
nakadi-java-client/src/main/java/nakadi/TokenProvider.java
nakadi-java-client/src/test/java/nakadi/EventResourceRealTest.java
nakadi-java-client/src/test/java/nakadi/EventTypeResourceRealTest.java
nakadi-java-client/src/test/java/nakadi/EventTypeTest.java
nakadi-java-client/src/test/java/nakadi/OkHttpResourceTest.java
nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java
nakadi-java-client/src/test/java/nakadi/StreamResourceSupportTest.java
nakadi-java-client/src/test/java/nakadi/SubscriptionResourceRealTest.java
nakadi-java-zign/src/main/java/nakadi/token/zign/TokenProviderZign.java
nakadi-java-zign/src/test/java/nakadi/token/zign/TokenProviderZignTest.java

This deprecates scopes on the client API. Scopes that are passed to the
client are ignored.
Nakadi removed scopes in https://github.com/zalando/nakadi/pull/722
For #228.

Deprecates scopes.

---

nakadi-java-client/src/main/java/nakadi/StreamBatchRecordSubscriber.java
nakadi-java-client/src/main/java/nakadi/StreamObserver.java
nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java

This replaces the onStart call when the consumer processor is setup with
a new onBegin method. The onStart should be called every time the
processor retries, but onBegin just once, avoiding a double call the
first time the processor spins up.

Removes duplicate Observer onStart call.

---

nakadi-java-client/src/main/java/nakadi/EventResourceReal.java
nakadi-java-client/src/main/java/nakadi/OkHttpResponse.java
nakadi-java-client/src/main/java/nakadi/OkHttpResponseBody.java
nakadi-java-client/src/main/java/nakadi/Response.java
nakadi-java-client/src/main/java/nakadi/SubscriptionResourceReal.java
nakadi-java-client/src/test/java/nakadi/ProblemSupportTest.java

A convenience method that delegates to the ResponseBody close
method. This might make it more obvious that Responses should
be closed by callers and is cleaner to use in a try with
resources block.
For #237.

Adds a close method to the Response interface.

---

nakadi-java-client/src/main/java/nakadi/GsonSupport.java
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java

This removes a conversion from a JsonObject to a String, and uses the
JsonObject directly for object marshalling. It also makes a best
effort to clear down an interm list of temp objects created during
marshalling.
It's not clear if client allocations are the cause of OOMs in #256 
but this seems like a reasonable overhead to avoid.
For #256.

Reduce allocations when marshalling events from a stream.

---

nakadi-java-client/src/main/java/nakadi/StreamConnectionRetryFlowable.java
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
nakadi-java-client/src/main/java/nakadi/StreamProcessorManaged.java
nakadi-java-client/src/test/java/nakadi/StreamProcessorTest.java

This signals that the number of retries for a processor have been
met so that the processor can perform a shutdown and clean up its
underlying resources via stopStreaming.
For #284.

Stops stream processor after retries are exceeded.

---

nakadi-java-client/src/main/java/nakadi/ExceptionSupport.java
nakadi-java-client/src/main/java/nakadi/StreamConfiguration.java
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java

The stream processor can absorb event batches sent by Nakadi into a
buffer managed by the I/O layer of the processor. Observers that can't
keep up with a stream will result in the batches being buffered to a
high number. This can cause memory pressure due to the buffer not
being drained quickly enough. Also the byte size of a batch can vary
greatly based on the underlying size of each event and the number of
events requested per batch (a multi-megabyte size batch is not unheard
of).
This lowers the default batch buffer count to 128, and allows the batch
buffer count to be set via stream configuration. It's expected this will
help consumers whose observers are relatively slow compared to the rate
of events being sent and read from the network. Observers that exceed
the buffer size will …

Lowers default batch buffer and allows setting by configuration. 

---

nakadi-java-client/src/main/java/nakadi/StreamObserver.java
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java

This calls onStop once, when the processor is being stopped. It also
documents onCompleted as being called after a processor has finished
due to being configure ot fetch only a subset. Previously onStop
was being called multiple times, for example on every retry.
For #289.

Calls StreamObserver.onStop only on termination.

---

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java
nakadi-java-client/src/main/java/nakadi/StreamProcessorRequestFactory.java

This checks in the onCompleted phase if the response was 200 OK and
whether the processor was configured with a stream_timeout. If so, it's
assumed the server closed a successful response due to the stream timeout
directive sent to it, and the processor will not retry. The 200 Ok check
allows other failure modes (such as authorization) to be retried.
For #291.

Stops the processor after a successful response with a stream timeout

---

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java

This checks in the onCancel phase if the response was 200 OK and
whether the processor was configured with a stream_timeout. If so, it's
assumed the server closed a successful response due to the stream timeout
directive sent to it, and the processor will not retry. The 200 Ok check
allows other failure modes (such as authorization) to be retried.
For #291.

Stops the processor after a successful response with a stream timeout.

---

.gitignore
nakadi-java-client/src/main/java/nakadi/StreamProcessor.java

Removes custom buffering from stream processor.
Previously when the library usd RxJava 1, buffering was added to
control backpressure between the http and observer layers in the
case when the observer couldn't keep up. Backpressure's been
changed in RxJava2 with the Flowable type the client uses. The
Flowable type handles backpressure more gracefully and removing
the custom settings from the RxJava 1 days seems to greatly
improve handling of events off the wire, eg streams
being consumed more or less indefinitely without retry and
disconnects.

Improve stream consumption handling

---

nakadi-java-client/src/main/java/nakadi/SubscriptionEventTypeStatsCollection.java
nakadi-java-client/src/test/java/nakadi/test/SubscriptionEventTypeStatsCollectionVisibilityTest.java

This allows for easier testing by end users.

Makes the SubscriptionEventTypeStatsCollection constructor public.

---

nakadi-java-client/src/main/java/nakadi/StreamProcessor.java

Not a bug, bus still looks suspicious of first sight.
This is more of a comment. I see that `StreamProcessor#stopping()` checks both `this.stopped` and `this.stopping` while in both cases when stopping is used both  `StreamProcessor#stopping()` and `StreamProcessor#stopped()` are invoked:
* `!stopping() && !stopped() && started()`  in `StreamProcessor#running()`
* `stopped() || stopping()` in in `StreamProcessor#start()`
So this looks redundant. That is `StreamProcessor#stopping()` could check only `this.stopping` without logic change, or, alternatively, leave only `StreamProcessor#stopped` that would check both.
Another comment is that using 3 state variables `stopping`, `stopped`, and `running` begs for inconsistencies (e.g. running == true and stopped == true), I would implemented it a …

Cleanup: use logical 'and' for booleans

---

nakadi-java-client/src/main/java/nakadi/MetricCollector.java
nakadi-java-client/src/main/java/nakadi/SubscriptionOffsetCheckpointer.java
nakadi-java-client/src/test/java/nakadi/SubscriptionOffsetCheckpointerTest.java
nakadi-java-client/src/test/resources/cursor-commit-result-1.json

This provides a consumer hook to view the CursorCommitResultCollection result
from the server, along with the initiating StreamCursorContext. If the
CursorCommitResultCollection.items() collection is empty (a 200 Ok) from the
server it means the server moved the cursor forward. If the
CursorCommitResultCollection.items() collection is not empty (a 204 No-Content)
it means the server ignored a stale cursor. A stale cursor is strongly
indicative of a local processing problem.
This change also adds metrics for the two result forms to the MetricCollector
object and calls the collector based on the server result.

Allows a consumer to see the checkpoint response result from the server.

---

README.md
nakadi-java-client/src/main/java/nakadi/EventMetadata.java
nakadi-java-client/src/test/java/nakadi/EventMetadataTest.java
nakadi-java-client/src/test/java/nakadi/EventResourceRealTest.java

The previous constructor had a performance overhead in creating
default values (especially for eid, which used UUID.randomUUID).
A prepared EventMetadata can be created using newPreparedEventMetadata
instead.
For #321.

Stops creating default values for EventMetadata.

---

CHANGES.md
gradle.properties
nakadi-java-client/src/main/java/nakadi/Version.java

2018/04/12: This is patch release forked from 0.8.5
- Suppresses logging of some unhandled exceptions from StreamProcessor.

0.8.5.1 (patch release from 0.8.5)

---

nakadi-java-client/src/main/java/nakadi/EventMetadata.java
nakadi-java-client/src/main/java/nakadi/EventType.java
nakadi-java-client/src/test/java/nakadi/EventMetadataTest.java
nakadi-java-client/src/test/java/nakadi/EventTypeTest.java
nakadi-java-client/src/test/java/nakadi/JsonBatchSupportTest.java
nakadi-java-client/src/test/resources/business-event-batch-1.json
nakadi-java-client/src/test/resources/event-type-1.json

Since Nakadi version 2.8.1 event types have now support for log
compaction. See the [API](https://nakadi.io/manual.html#definition_EventType*cleanup_policy) for more details.
Log compacted event types must specify an option `compact` cleanup
policy during creation. All events from log compacted event types must
contain `metadata.partition_compaction_key` in order for Nakadi to
perform compaction.
Events sent to event types that are **not** log compacted should **not** have `metadata.partition_compaction_key` in their metadata. That would cause rejection of events.
I understood that gson omits null values by default but I couldn't find tests for marshalling objects into bytes.

Support log compaction

---

nakadi-java-client/src/main/java/nakadi/UriBuilder.java
nakadi-java-client/src/test/java/nakadi/UriBuilderTest.java

This checks the URI string supplied to UriBuilder.builder
and if a trailing slash is found it's removed. It allows
configurations to not worry about whether the Nakadi base
URI has a trailing slash
For #330.

Strips trailing '/' from arg supplied to UriBuilder.builder.

---

CHANGES.md
README.md
gradle.properties
nakadi-java-client/src/main/java/nakadi/UriBuilder.java
nakadi-java-client/src/main/java/nakadi/Version.java
nakadi-java-client/src/test/java/nakadi/UriBuilderTest.java

Strips trailing '/' from arg supplied to UriBuilder.builder.
This checks the URI string supplied to UriBuilder.builder 
and if a trailing slash is found it's removed. It allows 
configurations to not worry about whether the Nakadi base 
URI has a trailing slash
For #330.

0.9.17 backport: Strips trailing '/' from arg supplied to UriBuilder.builder.

---

nakadi-java-client/src/main/java/nakadi/EventType.java
nakadi-java-client/src/test/java/nakadi/EventTypeTest.java
nakadi-java-client/src/test/resources/event-type-1.json

Fixes #348 by adding new field: `EventType.audience`
This solves the issue that clients cannot update event types having this field set because it does not get marshalled and Nakadi responds with an error, as recently Nakadi API began disallow setting `audience` to `null` once it has been specified.
Updated the unmarshalling unit tests.

Add 'audience' field to EventType model

---

nakadi-java-client/src/main/java/nakadi/StreamConfiguration.java
nakadi-java-client/src/main/java/nakadi/StreamResourceSupport.java

Adds commit_timeout parameter to configuration as described here:
https://nakadi.io/manual.html#/subscriptions/subscription_id/events_get*commit_timeout

Add commit_timeout parameter to stream configuration

---

README.md

Using bintray jcenter over HTTP is now unsupported: https://jfrog.com/jcenter-http/
So the instructions for adding the lib for SBT did not work anymore: the library doesn't resolve correctly with these settings.
This fixes it by using SBT's [predefined resolver definition for JCenter Bintray](https://www.scala-sbt.org/1.x/docs/Resolvers.html#Predefined+resolvers), which uses HTTPS.
Tested by following these instructions for using lib in my own Scala project, this resolves fine with the change.

Fix instructions for bintray jcenter

---

build.gradle
gradle.properties
gradle/libs.gradle
gradle/wrapper/gradle-wrapper.properties
nakadi-java-client/build.gradle
nakadi-java-client/src/main/java/nakadi/EventMetadata.java
nakadi-java-gson/build.gradle
nakadi-java-metrics/build.gradle
nakadi-java-zign/build.gradle

Converts the build to publish to sonatype
This replaces the bintray publication (bintray is gone) with a  maven publication to sonatype. In doing so it upgrades to use  more recent versions of gradle, shadow, and nebula plugins. It also adds signing support required by sonatype. The build's jar packaging step has to be rewritten as a result rather than just changing the publish target, so the version will get a major bump (effectively a promotion to 0.16 from 0.15) to be on the safe side.

Publish to oss.sonatype.org

---

nakadi-java-client/src/main/java/nakadi/Problem.java
nakadi-java-client/src/main/java/nakadi/ProblemSupport.java
nakadi-java-client/src/test/java/nakadi/ProblemSupportTest.java

https://github.com/dehora/nakadi-java/issues/357

non-json payloads on error responses are handled

---

nakadi-java-client/src/main/java/nakadi/EventResourceReal.java
nakadi-java-client/src/main/java/nakadi/EventTypeResourceReal.java
nakadi-java-client/src/main/java/nakadi/OkHttpResource.java
nakadi-java-client/src/main/java/nakadi/ResourceSupport.java
nakadi-java-client/src/main/java/nakadi/SubscriptionResourceReal.java
nakadi-java-client/src/test/java/nakadi/OkHttpResourceTest.java

The content type for post requests is always `application/json`, to make it dynamic now its read from headers. This will enable in future to add body with different content type.

Supply content type from headers

---

nakadi-java-client/src/main/java/nakadi/ResourceOptions.java
nakadi-java-client/src/main/java/nakadi/ResourceSupport.java
nakadi-java-client/src/test/java/nakadi/EventResourceRealTest.java
nakadi-java-client/src/test/java/nakadi/OkHttpResourceTest.java
nakadi-java-client/src/test/java/nakadi/ResourceOptionsTest.java
nakadi-java-client/src/test/java/nakadi/ResourceSupportTest.java
nakadi-java-client/src/test/java/nakadi/SubscriptionResourceRealTest.java

- Adds header convenience methods to ResourceOptions for clarity
- Adds tests to verify behaviour added in #379

Making room for more flexible content type handling

---

nakadi-java-client/src/main/java/nakadi/EventResourceReal.java
nakadi-java-client/src/main/java/nakadi/EventTypeSchema.java
nakadi-java-client/src/main/java/nakadi/JsonPublishingBatchSerializer.java
nakadi-java-client/src/main/java/nakadi/JsonSerializationSupport.java
nakadi-java-client/src/main/java/nakadi/NakadiClient.java
nakadi-java-client/src/main/java/nakadi/PublishingBatchSerializer.java
nakadi-java-client/src/main/java/nakadi/SerializationContext.java
nakadi-java-client/src/main/java/nakadi/SerializationSupport.java

This introduces some indirection to allow alternative (non-json)
serializers to be used. SerializationSupport is used by the client
to access a serializer, with JsonSerializationSupport providing the
current default for JSON payloads.

Starts adding support for non json events

---

gradle.properties
gradle/libs.gradle
nakadi-java-avro/build.gradle
nakadi-java-avro/src/main/java/nakadi/avro/InvalidEventTypeException.java
nakadi-java-avro/src/main/java/nakadi/avro/InvalidSchemaException.java
nakadi-java-avro/src/main/resources/nakadi-envelope-schema/batch.publishing.avsc
nakadi-java-avro/src/main/resources/nakadi-envelope-schema/envelope.avsc
nakadi-java-avro/src/test/java/nakadi/avro/AvroPublishingBatchSerializerTest.java

This provides a module skeleton for an avro extension to the client. The avro files for envelope and batch publishing along with some exceptions are here to bootstrap the gradle build.

Adds an avro module

---

nakadi-java-avro/src/main/java/nakadi/avro/AvroPublishingBatchSerializer.java
nakadi-java-avro/src/main/java/nakadi/avro/AvroSerializationSupport.java
nakadi-java-avro/src/test/java/nakadi/avro/AvroPublishingBatchSerializerTest.java

AvroSerializationSupport can be provide to the client to handle avro serialisation. The serialization targets avro binary rather than avro json formatting. AvroPublishingBatchSerializerTest shows business envelope serialisation with events pretty much identical to the tests in EventResourceRealTest from the main client module.
For development, the build will need to run once to create the generated avro files in the 'org.zalando.nakadi.*' package space.

Provides an initial avro implementation.

---

nakadi-java-client/src/main/java/nakadi/StreamBatchRecordBufferingSubscriber.java

Replaces call to the supplied StreamObserver's onStart with onBegin.
From: @fghibellini

Fixes incorrect implementation of onStart in buffered observers.
